# Spring Boot application configuration
server.port=${PORT:8080}
spring.application.name=db-analyser-api

spring.config.import=optional:file:.env.properties
# Disable standard spring datasource autoconfiguration since we connect dynamically using raw JDBC
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
