# Spring Boot application configuration
server.port=${PORT:8080}
spring.application.name=db-analyser-api

spring.config.import=optional:file:.env.properties
# Disable standard spring datasource autoconfiguration since we connect dynamically using raw JDBC
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

spark.engine.jar=${SPARK_ENGINE_JAR:../Spark-Engine/target/spark-engine.jar}
